/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot") version "3.3.2"
    id("io.spring.dependency-management") version "1.1.6"
    kotlin("jvm") version "1.8.20"
    id("java")
    id("application")
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_17

repositories {
    mavenCentral()
}


dependencies {
    // Spring Boot web dependency for REST APIs
    implementation("org.springframework.boot:spring-boot-starter-web")

    // Optional: Spring Boot Thymeleaf dependency for templating
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf")

    // Spring Boot development tools for live reload
    developmentOnly("org.springframework.boot:spring-boot-devtools")

     // JUnit 5 for testing - ensure same version across all JUnit dependencies
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.11.0")
    testImplementation("org.junit.platform:junit-platform-commons:1.11.0")
    testImplementation("org.junit.platform:junit-platform-engine:1.11.0")

    // Spring Boot testing support
    testImplementation("org.springframework.boot:spring-boot-starter-test") {
        exclude(module = "junit")
    }
}


tasks.test {
    useJUnitPlatform()
}

application {
    mainClass.set("app.App")
}