version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./express-frontend/public:/app/static
  
  frontend:
    build:
      context: ./express-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./express-frontend:/app

    environment:
      - BACKEND_URL=http://backend:8080
