version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # MongoDB default port
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - spring-mongo-network

  springboot-app:
    image: your-dockerhub-username/your-springboot-app:latest  # Or use build context below
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"  # Spring Boot default port
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/test?authSource=admin
    depends_on:
      - mongodb
    networks:
      - spring-mongo-network

volumes:
  mongo_data:
    driver: local

networks:
  spring-mongo-network:
    driver: bridge