/*
 * This source file was generated by the Gradle 'init' task
 */
package app.main;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

import app.App;

public class AppTest {

    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.greetUser("Test"), "app should have a greeting");
    }
}
