/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot") version "3.3.3"
    id("io.spring.dependency-management") version "1.1.0"
    id("java")
    id("application") 
    id("com.github.ben-manes.versions") version "0.47.0"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_17

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot web dependency for REST APIs
    implementation("org.springframework.boot:spring-boot-starter-web")

    // Optional: Spring Boot Thymeleaf dependency for templating
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf")

    // Spring Boot development tools for live reload
    developmentOnly("org.springframework.boot:spring-boot-devtools")

    // JUnit 5 for testing
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.0")

    // Spring Boot testing support
    testImplementation("org.springframework.boot:spring-boot-starter-test") {
        exclude(module = "junit")
    }
}

tasks.test {
    useJUnitPlatform()
}

application {
    mainClass.set("app.src.main.java.App")
}