/*
 * This source file was generated by the Gradle 'init' task
 */
package app.src.test.java;

import org.junit.jupiter.api.Test; // JUnit 5 import

import app.src.main.java.App;

import static org.junit.jupiter.api.Assertions.*; // JUnit 5 Assertions

public class AppTest {

    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.greetUser("Test"), "app should have a greeting");
    }
}

